//{{NO_DEPENDENCIES}}
// File di inclusione generato da Microsoft Visual C++.
// Usato da xmlRead.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_XMLREAD_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDD_STYLESHEET_SELECTOR	121
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDM_OPEN_ZIP			106
#define IDM_APPLY_MINISTERO		110
#define IDM_APPLY_ASSOSOFTWARE	111
#define IDM_CHANGE_STYLESHEET	112
#define IDM_TEST_BROWSER		113
#define IDM_PRINT_CURRENT		114
#define IDM_PRINT_ALL			115
#define IDM_PRINT_SELECTED		116
#define IDM_SETTINGS			117
#define IDM_SETTINGS_SELECT_STYLESHEET	118
#define IDM_PREV_FATTURA				119
#define IDM_NEXT_FATTURA				120
#define IDM_ZOOM_IN					122
#define IDM_ZOOM_OUT				123
#define IDM_PDF_SIGN_CONFIG			124
#define IDD_PDF_SIGN_CONFIG			125

// Menu contestuale ListBox
#define IDM_CONTEXT_PRINT_SELECTED  126
#define IDM_CONTEXT_CHANGE_STYLE    127
#define IDM_CONTEXT_VIEW_MINISTERO  128
#define IDM_CONTEXT_VIEW_ASSOSOFTWARE 129

#define IDC_ZOOM_LABEL				1007
#define IDC_TOOLBAR				1003
#define IDC_STATUSBAR			1004

// Risorse XSLT embedded
#define IDR_XSLT_MINISTERO		200
#define IDR_XSLT_ASSOSOFTWARE	201

#define IDI_XMLREAD			107
#define IDI_SMALL				108
#define IDC_XMLREAD			109
#define IDC_MYICON				2
#define IDC_LISTBOX_FATTURE		1001
#define IDC_STATIC_DISPLAY		1002
#define IDC_STYLESHEET_LIST		1005
#define IDC_STYLESHEET_PREVIEW	1006
#define IDC_CERT_PATH			1008
#define IDC_CERT_BROWSE			1009
#define IDC_CERT_PASSWORD		1010
#define IDC_ENABLE_SIGNING		1011
#define IDC_SIGN_REASON			1012
#define IDC_SIGN_LOCATION		1013
#define IDC_SIGN_CONTACT		1014
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Valori predefiniti successivi per i nuovi oggetti
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1003
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
